services:
  - type: web
    name: n8n
    env: docker
    image: n8nio/n8n:latest
    plan: free
    # Render skal vide, at n8n kører på port 5678
    ports:
      - internal: 5678
        protocol: http
